web_dynamic/views/auth.py
#!/usr/bin/python3
"""auth blueprint"""
from flask import Blueprint, render_template, request, redirect, flash, url_for, session, abort
from google.oauth2 import id_token
from google_auth_oauthlib.flow import Flow
from pip._vendor import cachecontrol
import google.auth.transport.requests
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User
from models import storage
import os
import pathlib

GOOGLE_CLIENT_ID = "239785008997-cvo4q3efusm4al8ag0hkav4dc47g7m56.apps.googleusercontent.com"

client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "client_secret.json")

flow = Flow.from_client_secrets_file(
    client_secrets_file=client_secrets_file,
    scopes=["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email", "openid"],
    redirect_uri="http://127.0.0.1:5000/register_user_post"
)



auth = Blueprint('auth', __name__)


def login_is_required(function):
    def wrapper(*args, **kwargs):
        if "google_id" not in session:
            return abort(401)  # Authorization required
        else:
            return function()

    return wrapper






@auth.route('/login')
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST', 'GET'])
def login_post():
    # OAuth log

    # password login
    username = request.form.get('username')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    user = storage._DBStorage__session.query(User).filter_by(user_name=username).first()
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return 'Error'
#    login_user(user)
    flash('Login successful', 'success')
    return redirect(url_for('main.profile'))


@auth.route('/register')
def register_user():
    return render_template('register.html')


@auth.route('/register_user_post', methods=['GET', 'POST'])
def register_user_post():
    flow.fetch_token(authorization_response=request.url)

    if not session["state"] == request.args["state"]:
        abort(500)  # State does not match!

    credentials = flow.credentials
    request_session = requests.session()
    cached_session = cachecontrol.CacheControl(request_session)
    token_request = google.auth.transport.requests.Request(session=cached_session)

    id_info = id_token.verify_oauth2_token(
        id_token=credentials._id_token,
        request=token_request,
        audience=GOOGLE_CLIENT_ID
    )

    session["google_id"] = id_info.get("sub")
    session["name"] = id_info.get("name")
    return session['name']

  


@auth.route('/logout')
def logout():
    return render_template('logout.html')


"""
  email = request.form.get('email')
    password = request.form.get('password')
    password = generate_password_hash(password, method='sha256')
    user_name = request.form.get('user_name')
    args = {'email': email, 'password': password, 'user_name': user_name}
    us2 = storage._DBStorage__session.query(User).filter_by(
        email=email).first()
    print(us2)
#    if us2:
 #       flash('Email already exists!')
  #      return render_template('register.html')
    user = User(**args)
    user.save()
    return redirect(url_for('auth.login'))
"""

web_dynamic/views/auth2.py
import os
import uuid
import pathlib
import requests
from flask import Blueprint, render_template, request, redirect, flash, url_for, session, abort, current_app
import requests
from google.oauth2 import id_token
from google_auth_oauthlib.flow import Flow
from pip._vendor import cachecontrol
import google.auth.transport.requests
from models.user import User
from models.redis import redis_client
from models import storage
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Mail, Message
from dotenv import load_dotenv

load_dotenv()

auth2 = Blueprint('auth2', __name__)



GOOGLE_CLIENT_ID = "239785008997-cvo4q3efusm4al8ag0hkav4dc47g7m56.apps.googleusercontent.com"

client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "client_secret.json")

flow = Flow.from_client_secrets_file(
    client_secrets_file=client_secrets_file,
    scopes=["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email", "openid"],
    redirect_uri="https://techinspire.tech/auth/callback"
)


def login_required(fun):
    """login_required wrapper function"""
    @wraps(fun)
    def fnc(*args, **kwargs):
        """decorated function"""
        if 'name' not in session:
            return redirect(url_for('auth2.login'))
        return fun(*args, **kwargs)
    return fnc

@auth2.route('/auth/login')
def login():
    return render_template('login.html')


@auth2.route("/auth/login/google")
def google_login():
    """Initiate google login. flow.authorization_url retuns a tuple of url and state"""
    authorization_url, state = flow.authorization_url()
    session["state"] = state
    return redirect(authorization_url)


@auth2.route("/auth/login/basic", methods=['POST'])
def basic_login():
    """Initiate basic login."""
    email = request.form.get('email')
    password = request.form.get('password')
    user = storage._DBStorage__session.query(User).filter_by(
        email=email).first()
    if user and check_password_hash(user.password, password):
        session['name'] = user.user_name
        token = uuid.uuid4()
        key = 'auth_{}'.format(token)
        redis_client.set(key, user.id)
        redis_client.expire(key, 24 * 60 * 60)
        session['token'] = token
        return redirect(url_for('auth2.protected_area'))
    flash('Please try again')
    return redirect(url_for('auth2.login'))


@auth2.route("/auth/callback")
def callback():
    """Callback function for google auth"""
    flow.fetch_token(authorization_response=request.url)

    #if not session["state"] == request.args["state"]:
    #   print('errrrors', session["state"], request.args["state"])
    #  abort(500)  # State does not match!

    credentials = flow.credentials
    request_session = requests.session()
    cached_session = cachecontrol.CacheControl(request_session)
    token_request = google.auth.transport.requests.Request(session=cached_session)
    # verify google_id_token token
    id_info = id_token.verify_oauth2_token(
        id_token=credentials._id_token,
        request=token_request,
        audience=GOOGLE_CLIENT_ID
    )

    session["google_id"] = id_info.get("sub")
    session["name"] = id_info.get("name")
    name = id_info.get("name")
    email = id_info.get('email')
    oauth_user_id = id_info.get('sub')
    user = storage._DBStorage__session.query(User).filter_by(
        email=email).first()
    if user:
        token = uuid.uuid4()
        key = 'auth_{}'.format(token)
        redis_client.set(key, user.id)
        redis_client.expire(key, 24 * 60 * 60)
        session['token'] = token
        return redirect(url_for('auth2.protected_area'))
    kwargs = {'user_name': name, 'email': email, 'oauth_provider': 'google', 'oauth_user_id': oauth_user_id}
    requests.post('https://techinspire.tech/api/v1/users', json=kwargs)
    send_email(email, name)
    return redirect(url_for('auth2.google_login'))


def send_confirmation_email(user_email, token, name):
    """Send confirmation email"""
    mail = Mail(current_app)
    with current_app.app_context():
        msg = Message('Confirm Your Email', recipients=[user_email])
        confirmation_url = url_for('auth2.confirm_email', token=token, _external=True)
        msg.html = render_template('email_confirm.html', name=name, confirmation_url=confirmation_url)
        mail.send(msg)


def send_email(user_email, name):
    """send email"""
    mail = Mail(current_app)
    with current_app.app_context():
        msg = Message('Welcome to ChatSphere', recipients=[user_email])
        msg.html = render_template('welcome.html', name=name)
        mail.send(msg)


@auth2.route('/auth/confirm/<string:token>')
def confirm_email(token):
    flash('Email confirmed successfully!')
    return redirect(url_for('auth2.login'))


@auth2.route('/auth/register')
def register():
    """render register template"""
    return render_template('register.html')


@auth2.route('/auth/register', methods=['POST'])
def register_user_post():
    """basic user registration"""
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    password = generate_password_hash(password, method='pbkdf2:sha256')
    user = storage._DBStorage__session.query(User).filter_by(
        email=email).first()
    if user:
        flash('Please try again')
        return redirect(url_for('auth2.register_user_post'))
    kwargs = {'user_name': username, 'email': email, 'password': password}
    token_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    token = token_serializer.dumps(email)
    send_confirmation_email(email, token, username)
    flash('Confirmation email sent to your inbox. Please confirm')
    requests.post('https://techinspire.tech/api/v1/users', json=kwargs)
    send_email(email, username)
    return render_template('confirm.html')


@auth2.route("/auth/logout")
def logout():
    """logout and clear session"""
    token =  session.get('token')
    if token:
        key = 'auth_{}'.format(token)
        redis_client.delete(key)
    session.clear()
    return redirect("/")


@auth2.route("/home")
@login_required
def protected_area():
    """Render home page"""
    return render_template('home.html')

web_dynamic/templates/0-chat.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="../static/styles/4-common.css?cache_id={{ cache_id }}">
    <link rel="stylesheet" type="text/css" href="../static/styles/3-header.css?cache_id={{ cache_id }}">
    <link rel="stylesheet" type="text/css" href="../static/styles/3-footer.css?cache_id={{ cache_id }}">
    <link rel="stylesheet" type="text/css" href="../static/styles/6-filters.css?cache_id={{ cache_id }}">
    <link type="text/css" rel="stylesheet" href="../static/styles/8-places.css?cache_id={{ cache_id }}">
    <link rel="icon" href="../static/images/icon.png?cache_id" />
    <title>SPEAKIT</title>
  </head>
  <body>
    <header>
      <div class="logo"></div>
    </header>
    <div class="container">
      <section class="filters">
	<div class="locations">
	  <h3>Posts</h3>
	  <h4>&nbsp;</h4>
	  <div class="popover">
	    <ul>
	      {% for user in userposts %}
	      <li>
		<h2>{{ user[0].first_name }}:</h2>
		<ul>
		  {% for post in user[1] %}
		  <li>{{ post.title }}</li>
		  {% endfor %}
		</ul>
	      </li>
	      {% endfor %}
	    </ul>
	  </div>
	</div>
      </section>
    </div>
  </body>
</html>

web_dynamic/templates/2-chat.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Talku Talku</title>
<link rel="stylesheet" href="../static/css/test.css">
</head>
<body>
<div class="container">
<header>
<img src="https://i.imgur.com/logo.png" alt="Talku Talku logo">
<h1>Talku Talku</h1>
<nav>
<a href="#">Anastacia</a>
<a href="#">Ademola Daniel</a>
<a href="#">Ada Eze</a>
<a href="#">Goliath Killer</a>
<a href="#">Stella Marris</a>
<a href="#">Real Madrid</a>
</nav>
</header>
<main>
<div class="messages">
<div class="message">
<img src="https://i.imgur.com/profile_pic.png" alt="Anastacia's profile picture">
<h2>Anastacia</h2>
<p>nice app, testing testing</p>
</div>
<div class="message">
<img src="https://i.imgur.com/profile_pic.png" alt="Anastacia's profile picture">
<h2>Anastacia</h2>
<p>was this what i asked you for → →</p>
</div>
<div class="message">
<img src="https://i.imgur.com/profile_pic.png" alt="Uche Dennis's profile picture">
<h2>Uche Dennis</h2>
<p>type your message here</p>
</div>
</div>
</main>
</div>
<script src="../static/js/index.js"></script>
</body>
</html>

web_dynamic/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-signin-client_id" content="239785008997-cvo4q3efusm4al8ag0hkav4dc47g7m56.apps.googleusercontent.com">
  <title>Confirm email</title>
  <link rel="stylesheet" href="../static/css/register.css">
  <link rel="icon" href="../static/images/avatars/favicon16.jpg">
  </head>
<body>
  <div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification">
      <p>{{ messages[0] }}.</p>
    </div>
    {% endif %}
    {% endwith %}
  </div>
  <footer>
    <p>Copyright &copy; 2023 Francis Kamau. All rights reserved.</p>
  </footer>
</body>
</html>

web_dynamic/templates/email_confirm.html
<!-- templates/welcome_email.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link ref=""rel="stylesheet" href="../static/css/confirm.css">
    <title>Welcome to ChatSphere</title>
</head>
<body>
  <article>
    <h4>Hi {{ name }},</h4>
    <p>Thank you for joining ChatSphere!</p>
    <p>Please confirm your email by clicking the following link:</p>
    <button type="button"><a href="{{ confirmation_url }}">Confirm email</a></button>
    <p>Best regards,</p>
    <p>The ChatSphere Team</p>
    </article>
</body>
</html>

web_dynamic/templates/home.html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/2c.css">
    <link rel="icon" href="../static/images/avatars/favicon32.jpg">
        <link rel="icon" href="../static/images/avatars/favicon16.jpg">
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/image.css' rel='stylesheet'>
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/chevron-right.css' rel='stylesheet'>
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/log-out.css' rel='stylesheet'>
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/menu.css' rel='stylesheet'>
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/arrow-right.css' rel='stylesheet'>
    <link href='https://unpkg.com/css.gg@2.0.0/icons/css/arrow-left.css' rel='stylesheet'>
    <title>ChatSphere | home</title>
  </head>
  <body id="body">
    <div class="chat-container">
      <div data-role="page" class="side-bar" id="side-bar">
	<div class="logo-header">
	  <img src="../static/images/avatars/chat_logo.jpg">
	  <p>ChatSphere</p>
	</div>
        <div class="users-list">
            <!-- User names will be dynamically added here -->
        </div>
      </div>
      <div class="chat-area" id="chats">
	<div class="chat-header">
	  <i class="gg-arrow-left back"></i>
	  <div class="user-header"></div>
	  <div class="right-nav">
	    <div class="current-user">
	      <div class="user-image"></div>
	      <p class="user">{{ session['name'] }}</p>
	      <div class="user-menu">
		<div class="menu">
		  <i class="gg-menu"></i>
		</div>
		<ul class="menu-list">
		  <li>
		    <input type="file" id="imageInput" style="display:none;">
		    <a href="#" id="uploadButton"><p>Upload profile picture</p></a>
		  </li>
		  <li>
		    <a href="#" class="more-settings"><p>More settings</p></a>
		  </li>
		</ul>
	      </div>
	    </div>
	    <div class="header-button"><a href="{{ url_for('auth2.logout')}}"><i class="gg-log-out"></i></a></div>
	  </div>
	</div>
	<form class="settings">
	  <button type="button" class="arrow"><i class="gg-arrow-right"></i></button>
	  <label for"username">Username</label>
	  <div class="form-input">
	    <input type="text" name="username" placeholder="{{ session['name']}}" autofocus>
	    <button title="click to save" type="submit" class="update-info"><i class="gg-chevron-right"></i></button>
	  </div>
	  <p>Privacy</p>
	  <p>Notifications</p>
	  <p>Themes</p>
	</form>
	<div class="messages" id="messages-container">
                <!-- Messages will be dynamically added here -->

	</div>
	<div class="typing-indicator" id="typing-indicator"></div>
	<div class="message-input">
          <textarea id="message-input" placeholder="Type your message..." oninput='toggleSendButton()'></textarea>
	  <label for="file-input" class="file-label"><i class="gg-image"></i></label>
	  <input type="file" id="file-input" accept="image/*" onChange='toggleSendButton()'>

	  <button type="button" id="send-button"><i class="gg-chevron-right"></i></button>
	</div>

      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="../static/js/t.js"></script>
  </body>
</html>

web_dynamic/templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ChatSphere | The Seamless Messaging Platform </title>
  <link rel="stylesheet" href="../static/css/landing.css">
  <link rel="icon" href="../static/images/avatars/favicon16.jpg">
</head>
<body>
  <div class="container">
    <div class="nav">
      <a href="#">Home</a>
      <a href="#">Features</a>
      <a href="#">Privacy</a>
      <a href="#" class="about">About</a>
      <a href="{{ url_for('auth2.login') }}" class="login">Log in</a>
      <a href="{{ url_for('auth2.register') }}" class="btn top">Start messaging</a>

    </div>

    <header>
      <div class="head-cls">
	<div class="welcome">
	  <h1>Experience the full spectrum of connection: ChatSphere - Where every exchange is a visual symphony</h1>
	  <p>Experience seamless connections with the most secure and reliable messaging platform.Use ChatSphere to start and join conversations.</p>
	  <a href="{{ url_for('auth2.register_user_post') }}" class="btn">Start connecting</a>
	</div>
	<div class="image">
	  <img src="/static/images/avatars/landing_page.png">
	</div>
      </div>
  </header>

  <section class="features">
    <div class="feature">
      <div class="feature-txt">
      <h2>Connecting you with everyone, everywhere</h2>
      <p>Experience universal connectivity with ChatSphere, the messaging app that seamlessly bridges the gap between your family, friends, and colleagues, ensuring you're always connected to the people who matter</p>
      </div>
      <div class="image">
	<img src="/static/images/avatars/conv.png">
      </div>

    </div>


    <div class="feature f2">
      <div class="feature-txt">
      <h2>Guardians of your conversations; where private messaging takes center stage</h2>
      <p>Experience the assurance of confidential communication with ChatSphere as we prioritize the security of your conversations. In this messaging platform, private messaging is not just a feature; it's at the forefront, offering a trusted space for your most personal exchanges</p>
      </div>
      <div class="image">
	<img src="/static/images/avatars/landing_page.png">
      </div>

    </div>

    <div class="feature">
      <div class="feature-txt">
      <h2>Amplify conversations with dynamic visuals and rich media.</h2>
      <p>Unleashing the expressive power of ChatSphere means more than just words – it's a dynamic communication platform where your messages come alive through vibrant visuals and compelling media, enhancing the depth and impact of every interaction</p>
      </div>
      <div class="image">
	<img src="/static/images/avatars/ju.png">
      </div>

      </div>
  </section>

  <section class="cta">
    <h2>Start elevating your conversations with ChatSphere today</h2>
    <a href="{{ url_for('auth2.register_user_post') }}" class="btn">Start connecting</a>
  </section>

  <footer>
    <p>&copy; 2024 Francis Kamau. All rights reserved.</p>
  </footer>
  </div>
</body>
</html>

web_dynamic/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ChatSphere | Sign in</title>
  <link rel="stylesheet" href="../static/css/login.css">
  <link rel="icon" href="../static/images/avatars/favicon16.jpg">
</head>
<body>
  <div class="container">
    <div class="login-container">
    <form id="loginForm" method="post" action="{{ url_for('auth2.basic_login') }}">
      {% with messages = get_flashed_messages() %}
{% if messages %}
      <div class="notification is-danger">
        <p>{{ messages[0] }}</p>
      </div>
      {% endif %}
      {% endwith %}

	<div class="logo-header">
	  <img src="../static/images/avatars/chat_logo.jpg">
	  <strong>ChatSphere</strong>
	</div>

      <label for="email">Email</label>
      <input type="email" id="email" name="email" required autofocus>

      <label for="password">Password</label>
      <input type="password" id="password" name="password" required>
      <label class="checkbox">
        <input type="checkbox" name="remember">
        <p>Remember me</p>
      </label>
      <button type="submit">Login</button>
    </form>
          <a href="{{ url_for('auth2.google_login') }}">
<button type="button" class="gsi-material-button">
  <div class="gsi-material-button-state"></div>
  <div class="gsi-material-button-content-wrapper">
    <div class="gsi-material-button-icon">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
        <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
        <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
        <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
        <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
        <path fill="none" d="M0 0h48v48H0z"></path>
      </svg>
    </div>
    <span class="gsi-material-button-contents">Sign in with Google</span>
    <span style="display: none;">Sign in with Google</span>
  </div>
</button>
      </a>
    </div>
  </div>
    <footer>
      <p>Copyright &copy; 2023 Francis Kamau. All rights reserved.</p>
    </footer>

</body>
</html>

web_dynamic/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Registration</title>
  <link rel="stylesheet" href="../static/css/register.css">
  <link rel="icon" href="../static/images/avatars/favicon16.jpg">
  </head>
<body>
  <div class="login-container">
  <form id="registrationForm" method="post" action="{{ url_for('auth.register_user_post') }}">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification">
      <div class="message">{{ messages[0] }}.</div>
      <div>Go to <a href="{{ url_for('auth.login') }}">login page</a>.</div>
    </div>
    {% endif %}
    {% endwith %}
  <label for="username">Username:</label>
  <input type="text" id="username" placeholder="username" name="user_name" value="ryder" required>

  <label for="email">Email</label>
  <input type="email" id="email" placeholder="email" name="email" value="vamps@gmail.com"required>

  <label for="password">Password</label>
  <input type="password" id="password" placeholder="password" name="password" value="ride@fun" required>

  <button type="submit">Register</button>
    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login</a></p>

  <a href="{{ url_for('auth.google.login') }}">
    <button type="button" class="gsi-material-button">
      <div class="gsi-material-button-state"></div>
      <div class="gsi-material-button-content-wrapper">
	<div class="gsi-material-button-icon">
	  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
            <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
            <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
            <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
            <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
            <path fill="none" d="M0 0h48v48H0z"></path>
	  </svg>
	</div>
	<span class="gsi-material-button-contents">Sign up with Google</span>
	<span style="display: none;">Sign up with Google</span>
      </div>
    </button>
  </a>
  </form>
  </div>
  <script src="../static/js/register.js"></script>
</body>
</html>